package main

import (
	"github.com/amazon-sagemaker-service/mcp-server/config"
	"github.com/amazon-sagemaker-service/mcp-server/models"
	tools_x_amz_target_sagemaker_describemodelbiasjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelbiasjobdefinition"
	tools_x_amz_target_sagemaker_describeworkforce "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeworkforce"
	tools_x_amz_target_sagemaker_describetrial "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describetrial"
	tools_x_amz_target_sagemaker_describealgorithm "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describealgorithm"
	tools_x_amz_target_sagemaker_listworkforces "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listworkforces"
	tools_x_amz_target_sagemaker_deletestudiolifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletestudiolifecycleconfig"
	tools_x_amz_target_sagemaker_describelabelingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describelabelingjob"
	tools_x_amz_target_sagemaker_deletenotebookinstancelifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletenotebookinstancelifecycleconfig"
	tools_x_amz_target_sagemaker_listhubcontents "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listhubcontents"
	tools_x_amz_target_sagemaker_listtransformjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtransformjobs"
	tools_x_amz_target_sagemaker_describeimage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeimage"
	tools_x_amz_target_sagemaker_listexperiments "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listexperiments"
	tools_x_amz_target_sagemaker_createproject "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createproject"
	tools_x_amz_target_sagemaker_listcompilationjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listcompilationjobs"
	tools_x_amz_target_sagemaker_deletemodelexplainabilityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelexplainabilityjobdefinition"
	tools_x_amz_target_sagemaker_describeimageversion "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeimageversion"
	tools_x_amz_target_sagemaker_listlabelingjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listlabelingjobs"
	tools_x_amz_target_sagemaker_createendpoint "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createendpoint"
	tools_x_amz_target_sagemaker_listspaces "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listspaces"
	tools_x_amz_target_sagemaker_updatetrainingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatetrainingjob"
	tools_x_amz_target_sagemaker_listmodelcardexportjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelcardexportjobs"
	tools_x_amz_target_sagemaker_describeedgepackagingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeedgepackagingjob"
	tools_x_amz_target_sagemaker_updatemonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatemonitoringschedule"
	tools_x_amz_target_sagemaker_listsubscribedworkteams "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listsubscribedworkteams"
	tools_x_amz_target_sagemaker_updateendpointweightsandcapacities "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateendpointweightsandcapacities"
	tools_x_amz_target_sagemaker_listmonitoringexecutions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmonitoringexecutions"
	tools_x_amz_target_sagemaker_createaction "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createaction"
	tools_x_amz_target_sagemaker_registerdevices "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_registerdevices"
	tools_x_amz_target_sagemaker_createexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createexperiment"
	tools_x_amz_target_sagemaker_describeappimageconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeappimageconfig"
	tools_x_amz_target_sagemaker_describefeaturegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describefeaturegroup"
	tools_x_amz_target_sagemaker_deleteartifact "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteartifact"
	tools_x_amz_target_sagemaker_listlabelingjobsforworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listlabelingjobsforworkteam"
	tools_x_amz_target_sagemaker_createdomain "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createdomain"
	tools_x_amz_target_sagemaker_createtrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createtrialcomponent"
	tools_x_amz_target_sagemaker_listimageversions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listimageversions"
	tools_x_amz_target_sagemaker_describeedgedeploymentplan "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeedgedeploymentplan"
	tools_x_amz_target_sagemaker_updateaction "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateaction"
	tools_x_amz_target_sagemaker_deletetags "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletetags"
	tools_x_amz_target_sagemaker_deletemodel "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodel"
	tools_x_amz_target_sagemaker_describeendpoint "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeendpoint"
	tools_x_amz_target_sagemaker_describeapp "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeapp"
	tools_x_amz_target_sagemaker_createimageversion "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createimageversion"
	tools_x_amz_target_sagemaker_listmonitoringschedules "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmonitoringschedules"
	tools_x_amz_target_sagemaker_updatepipeline "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatepipeline"
	tools_x_amz_target_sagemaker_updateendpoint "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateendpoint"
	tools_x_amz_target_sagemaker_createedgepackagingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createedgepackagingjob"
	tools_x_amz_target_sagemaker_describeproject "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeproject"
	tools_x_amz_target_sagemaker_describemonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemonitoringschedule"
	tools_x_amz_target_sagemaker_deleteendpoint "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteendpoint"
	tools_x_amz_target_sagemaker_updatetrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatetrialcomponent"
	tools_x_amz_target_sagemaker_listhubcontentversions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listhubcontentversions"
	tools_x_amz_target_sagemaker_stopnotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopnotebookinstance"
	tools_x_amz_target_sagemaker_listdataqualityjobdefinitions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listdataqualityjobdefinitions"
	tools_x_amz_target_sagemaker_listartifacts "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listartifacts"
	tools_x_amz_target_sagemaker_updatecontext "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatecontext"
	tools_x_amz_target_sagemaker_deleteproject "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteproject"
	tools_x_amz_target_sagemaker_describeexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeexperiment"
	tools_x_amz_target_sagemaker_describetrainingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describetrainingjob"
	tools_x_amz_target_sagemaker_listaliases "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listaliases"
	tools_x_amz_target_sagemaker_deletefeaturegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletefeaturegroup"
	tools_x_amz_target_sagemaker_listtrainingjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtrainingjobs"
	tools_x_amz_target_sagemaker_describemodelcard "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelcard"
	tools_x_amz_target_sagemaker_updatetrial "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatetrial"
	tools_x_amz_target_sagemaker_listresourcecatalogs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listresourcecatalogs"
	tools_x_amz_target_sagemaker_updateartifact "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateartifact"
	tools_x_amz_target_sagemaker_listactions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listactions"
	tools_x_amz_target_sagemaker_createnotebookinstancelifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createnotebookinstancelifecycleconfig"
	tools_x_amz_target_sagemaker_listuserprofiles "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listuserprofiles"
	tools_x_amz_target_sagemaker_listhubs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listhubs"
	tools_x_amz_target_sagemaker_deleteworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteworkteam"
	tools_x_amz_target_sagemaker_createalgorithm "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createalgorithm"
	tools_x_amz_target_sagemaker_startinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_startinferenceexperiment"
	tools_x_amz_target_sagemaker_startpipelineexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_startpipelineexecution"
	tools_x_amz_target_sagemaker_updatespace "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatespace"
	tools_x_amz_target_sagemaker_deleteedgedeploymentstage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteedgedeploymentstage"
	tools_x_amz_target_sagemaker_updateinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateinferenceexperiment"
	tools_x_amz_target_sagemaker_updatecoderepository "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatecoderepository"
	tools_x_amz_target_sagemaker_listappimageconfigs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listappimageconfigs"
	tools_x_amz_target_sagemaker_updateworkforce "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateworkforce"
	tools_x_amz_target_sagemaker_updatepipelineexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatepipelineexecution"
	tools_x_amz_target_sagemaker_listdevices "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listdevices"
	tools_x_amz_target_sagemaker_stopcompilationjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopcompilationjob"
	tools_x_amz_target_sagemaker_createmodelexplainabilityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelexplainabilityjobdefinition"
	tools_x_amz_target_sagemaker_describemodelcardexportjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelcardexportjob"
	tools_x_amz_target_sagemaker_updatehub "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatehub"
	tools_x_amz_target_sagemaker_updatedomain "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatedomain"
	tools_x_amz_target_sagemaker_updateproject "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateproject"
	tools_x_amz_target_sagemaker_stopinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopinferenceexperiment"
	tools_x_amz_target_sagemaker_createappimageconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createappimageconfig"
	tools_x_amz_target_sagemaker_describeprocessingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeprocessingjob"
	tools_x_amz_target_sagemaker_listtrainingjobsforhyperparametertuningjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtrainingjobsforhyperparametertuningjob"
	tools_x_amz_target_sagemaker_deletedomain "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletedomain"
	tools_x_amz_target_sagemaker_listflowdefinitions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listflowdefinitions"
	tools_x_amz_target_sagemaker_createpresignednotebookinstanceurl "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createpresignednotebookinstanceurl"
	tools_x_amz_target_sagemaker_describeartifact "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeartifact"
	tools_x_amz_target_sagemaker_createdevicefleet "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createdevicefleet"
	tools_x_amz_target_sagemaker_stopautomljob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopautomljob"
	tools_x_amz_target_sagemaker_updatedevices "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatedevices"
	tools_x_amz_target_sagemaker_updatemodelcard "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatemodelcard"
	tools_x_amz_target_sagemaker_deletemodelpackagegrouppolicy "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelpackagegrouppolicy"
	tools_x_amz_target_sagemaker_deleteinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteinferenceexperiment"
	tools_x_amz_target_sagemaker_getsagemakerservicecatalogportfoliostatus "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getsagemakerservicecatalogportfoliostatus"
	tools_x_amz_target_sagemaker_getsearchsuggestions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getsearchsuggestions"
	tools_x_amz_target_sagemaker_addassociation "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_addassociation"
	tools_x_amz_target_sagemaker_describemodelexplainabilityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelexplainabilityjobdefinition"
	tools_x_amz_target_sagemaker_describeworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeworkteam"
	tools_x_amz_target_sagemaker_describeautomljobv2 "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeautomljobv2"
	tools_x_amz_target_sagemaker_createinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createinferenceexperiment"
	tools_x_amz_target_sagemaker_createuserprofile "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createuserprofile"
	tools_x_amz_target_sagemaker_listinferenceexperiments "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listinferenceexperiments"
	tools_x_amz_target_sagemaker_describeautomljob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeautomljob"
	tools_x_amz_target_sagemaker_stoplabelingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stoplabelingjob"
	tools_x_amz_target_sagemaker_describeinferencerecommendationsjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeinferencerecommendationsjob"
	tools_x_amz_target_sagemaker_describemodel "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodel"
	tools_x_amz_target_sagemaker_deletemodelpackage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelpackage"
	tools_x_amz_target_sagemaker_createpresigneddomainurl "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createpresigneddomainurl"
	tools_x_amz_target_sagemaker_updateexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateexperiment"
	tools_x_amz_target_sagemaker_stopmonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopmonitoringschedule"
	tools_x_amz_target_sagemaker_describespace "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describespace"
	tools_x_amz_target_sagemaker_listapps "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listapps"
	tools_x_amz_target_sagemaker_updatemodelpackage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatemodelpackage"
	tools_x_amz_target_sagemaker_describeflowdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeflowdefinition"
	tools_x_amz_target_sagemaker_listedgedeploymentplans "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listedgedeploymentplans"
	tools_x_amz_target_sagemaker_createhub "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createhub"
	tools_x_amz_target_sagemaker_listworkteams "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listworkteams"
	tools_x_amz_target_sagemaker_listfeaturegroups "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listfeaturegroups"
	tools_x_amz_target_sagemaker_stopprocessingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopprocessingjob"
	tools_x_amz_target_sagemaker_describepipelinedefinitionforexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describepipelinedefinitionforexecution"
	tools_x_amz_target_sagemaker_listhumantaskuis "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listhumantaskuis"
	tools_x_amz_target_sagemaker_listmodelcards "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelcards"
	tools_x_amz_target_sagemaker_describeuserprofile "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeuserprofile"
	tools_x_amz_target_sagemaker_createcoderepository "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createcoderepository"
	tools_x_amz_target_sagemaker_listnotebookinstances "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listnotebookinstances"
	tools_x_amz_target_sagemaker_deletetrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletetrialcomponent"
	tools_x_amz_target_sagemaker_listassociations "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listassociations"
	tools_x_amz_target_sagemaker_listedgepackagingjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listedgepackagingjobs"
	tools_x_amz_target_sagemaker_stoptransformjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stoptransformjob"
	tools_x_amz_target_sagemaker_deletenotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletenotebookinstance"
	tools_x_amz_target_sagemaker_sendpipelineexecutionstepfailure "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_sendpipelineexecutionstepfailure"
	tools_x_amz_target_sagemaker_listtrialcomponents "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtrialcomponents"
	tools_x_amz_target_sagemaker_describedataqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describedataqualityjobdefinition"
	tools_x_amz_target_sagemaker_describenotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describenotebookinstance"
	tools_x_amz_target_sagemaker_deleteimage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteimage"
	tools_x_amz_target_sagemaker_createworkforce "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createworkforce"
	tools_x_amz_target_sagemaker_createimage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createimage"
	tools_x_amz_target_sagemaker_createartifact "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createartifact"
	tools_x_amz_target_sagemaker_createapp "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createapp"
	tools_x_amz_target_sagemaker_listmodelexplainabilityjobdefinitions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelexplainabilityjobdefinitions"
	tools_x_amz_target_sagemaker_deletetrial "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletetrial"
	tools_x_amz_target_sagemaker_createedgedeploymentplan "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createedgedeploymentplan"
	tools_x_amz_target_sagemaker_deleteflowdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteflowdefinition"
	tools_x_amz_target_sagemaker_deletealgorithm "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletealgorithm"
	tools_x_amz_target_sagemaker_listmodelcardversions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelcardversions"
	tools_x_amz_target_sagemaker_listprocessingjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listprocessingjobs"
	tools_x_amz_target_sagemaker_createmodelqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelqualityjobdefinition"
	tools_x_amz_target_sagemaker_deletemonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemonitoringschedule"
	tools_x_amz_target_sagemaker_describenotebookinstancelifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describenotebookinstancelifecycleconfig"
	tools_x_amz_target_sagemaker_putmodelpackagegrouppolicy "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_putmodelpackagegrouppolicy"
	tools_x_amz_target_sagemaker_deleteendpointconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteendpointconfig"
	tools_x_amz_target_sagemaker_deletepipeline "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletepipeline"
	tools_x_amz_target_sagemaker_createspace "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createspace"
	tools_x_amz_target_sagemaker_createmodel "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodel"
	tools_x_amz_target_sagemaker_stopedgepackagingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopedgepackagingjob"
	tools_x_amz_target_sagemaker_deleteapp "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteapp"
	tools_x_amz_target_sagemaker_startedgedeploymentstage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_startedgedeploymentstage"
	tools_x_amz_target_sagemaker_liststudiolifecycleconfigs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_liststudiolifecycleconfigs"
	tools_x_amz_target_sagemaker_createhyperparametertuningjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createhyperparametertuningjob"
	tools_x_amz_target_sagemaker_deletemodelqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelqualityjobdefinition"
	tools_x_amz_target_sagemaker_listpipelineparametersforexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listpipelineparametersforexecution"
	tools_x_amz_target_sagemaker_describeendpointconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeendpointconfig"
	tools_x_amz_target_sagemaker_updateimageversion "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateimageversion"
	tools_x_amz_target_sagemaker_updatenotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatenotebookinstance"
	tools_x_amz_target_sagemaker_search "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_search"
	tools_x_amz_target_sagemaker_createmodelpackagegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelpackagegroup"
	tools_x_amz_target_sagemaker_createpipeline "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createpipeline"
	tools_x_amz_target_sagemaker_stophyperparametertuningjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stophyperparametertuningjob"
	tools_x_amz_target_sagemaker_retrypipelineexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_retrypipelineexecution"
	tools_x_amz_target_sagemaker_getlineagegrouppolicy "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getlineagegrouppolicy"
	tools_x_amz_target_sagemaker_listdevicefleets "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listdevicefleets"
	tools_x_amz_target_sagemaker_updatedevicefleet "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatedevicefleet"
	tools_x_amz_target_sagemaker_describetrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describetrialcomponent"
	tools_x_amz_target_sagemaker_deletehub "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletehub"
	tools_x_amz_target_sagemaker_listcontexts "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listcontexts"
	tools_x_amz_target_sagemaker_stopedgedeploymentstage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopedgedeploymentstage"
	tools_x_amz_target_sagemaker_listcoderepositories "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listcoderepositories"
	tools_x_amz_target_sagemaker_createtransformjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createtransformjob"
	tools_x_amz_target_sagemaker_describemodelpackagegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelpackagegroup"
	tools_x_amz_target_sagemaker_listmodels "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodels"
	tools_x_amz_target_sagemaker_describeaction "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeaction"
	tools_x_amz_target_sagemaker_updateimage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateimage"
	tools_x_amz_target_sagemaker_describelineagegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describelineagegroup"
	tools_x_amz_target_sagemaker_startnotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_startnotebookinstance"
	tools_x_amz_target_sagemaker_listlineagegroups "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listlineagegroups"
	tools_x_amz_target_sagemaker_createtrial "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createtrial"
	tools_x_amz_target_sagemaker_describecoderepository "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describecoderepository"
	tools_x_amz_target_sagemaker_listnotebookinstancelifecycleconfigs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listnotebookinstancelifecycleconfigs"
	tools_x_amz_target_sagemaker_createmonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmonitoringschedule"
	tools_x_amz_target_sagemaker_listendpointconfigs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listendpointconfigs"
	tools_x_amz_target_sagemaker_deletecontext "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletecontext"
	tools_x_amz_target_sagemaker_listautomljobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listautomljobs"
	tools_x_amz_target_sagemaker_listtrials "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtrials"
	tools_x_amz_target_sagemaker_createnotebookinstance "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createnotebookinstance"
	tools_x_amz_target_sagemaker_describehub "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describehub"
	tools_x_amz_target_sagemaker_listtags "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listtags"
	tools_x_amz_target_sagemaker_deletedataqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletedataqualityjobdefinition"
	tools_x_amz_target_sagemaker_createautomljob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createautomljob"
	tools_x_amz_target_sagemaker_describestudiolifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describestudiolifecycleconfig"
	tools_x_amz_target_sagemaker_describehyperparametertuningjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describehyperparametertuningjob"
	tools_x_amz_target_sagemaker_startmonitoringschedule "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_startmonitoringschedule"
	tools_x_amz_target_sagemaker_deleteassociation "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteassociation"
	tools_x_amz_target_sagemaker_querylineage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_querylineage"
	tools_x_amz_target_sagemaker_listpipelines "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listpipelines"
	tools_x_amz_target_sagemaker_describedomain "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describedomain"
	tools_x_amz_target_sagemaker_updatemonitoringalert "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatemonitoringalert"
	tools_x_amz_target_sagemaker_deletedevicefleet "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletedevicefleet"
	tools_x_amz_target_sagemaker_updatefeaturemetadata "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatefeaturemetadata"
	tools_x_amz_target_sagemaker_listdomains "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listdomains"
	tools_x_amz_target_sagemaker_sendpipelineexecutionstepsuccess "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_sendpipelineexecutionstepsuccess"
	tools_x_amz_target_sagemaker_deletemodelbiasjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelbiasjobdefinition"
	tools_x_amz_target_sagemaker_addtags "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_addtags"
	tools_x_amz_target_sagemaker_listinferencerecommendationsjobsteps "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listinferencerecommendationsjobsteps"
	tools_x_amz_target_sagemaker_getdevicefleetreport "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getdevicefleetreport"
	tools_x_amz_target_sagemaker_listmodelqualityjobdefinitions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelqualityjobdefinitions"
	tools_x_amz_target_sagemaker_getscalingconfigurationrecommendation "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getscalingconfigurationrecommendation"
	tools_x_amz_target_sagemaker_createlabelingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createlabelingjob"
	tools_x_amz_target_sagemaker_describehumantaskui "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describehumantaskui"
	tools_x_amz_target_sagemaker_createflowdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createflowdefinition"
	tools_x_amz_target_sagemaker_deleteexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteexperiment"
	tools_x_amz_target_sagemaker_stopinferencerecommendationsjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stopinferencerecommendationsjob"
	tools_x_amz_target_sagemaker_createmodelcardexportjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelcardexportjob"
	tools_x_amz_target_sagemaker_getmodelpackagegrouppolicy "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_getmodelpackagegrouppolicy"
	tools_x_amz_target_sagemaker_describepipelineexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describepipelineexecution"
	tools_x_amz_target_sagemaker_listinferencerecommendationsjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listinferencerecommendationsjobs"
	tools_x_amz_target_sagemaker_describeinferenceexperiment "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describeinferenceexperiment"
	tools_x_amz_target_sagemaker_listendpoints "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listendpoints"
	tools_x_amz_target_sagemaker_listmodelpackages "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelpackages"
	tools_x_amz_target_sagemaker_batchdescribemodelpackage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_batchdescribemodelpackage"
	tools_x_amz_target_sagemaker_createhumantaskui "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createhumantaskui"
	tools_x_amz_target_sagemaker_stoptrainingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stoptrainingjob"
	tools_x_amz_target_sagemaker_describesubscribedworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describesubscribedworkteam"
	tools_x_amz_target_sagemaker_renderuitemplate "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_renderuitemplate"
	tools_x_amz_target_sagemaker_updatenotebookinstancelifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatenotebookinstancelifecycleconfig"
	tools_x_amz_target_sagemaker_createmodelcard "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelcard"
	tools_x_amz_target_sagemaker_describemodelqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelqualityjobdefinition"
	tools_x_amz_target_sagemaker_updatefeaturegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updatefeaturegroup"
	tools_x_amz_target_sagemaker_describefeaturemetadata "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describefeaturemetadata"
	tools_x_amz_target_sagemaker_createendpointconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createendpointconfig"
	tools_x_amz_target_sagemaker_listmodelbiasjobdefinitions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelbiasjobdefinitions"
	tools_x_amz_target_sagemaker_importhubcontent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_importhubcontent"
	tools_x_amz_target_sagemaker_listpipelineexecutionsteps "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listpipelineexecutionsteps"
	tools_x_amz_target_sagemaker_describecompilationjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describecompilationjob"
	tools_x_amz_target_sagemaker_describedevicefleet "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describedevicefleet"
	tools_x_amz_target_sagemaker_describedevice "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describedevice"
	tools_x_amz_target_sagemaker_listmonitoringalerthistory "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmonitoringalerthistory"
	tools_x_amz_target_sagemaker_deleteaction "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteaction"
	tools_x_amz_target_sagemaker_deletehubcontent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletehubcontent"
	tools_x_amz_target_sagemaker_describetransformjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describetransformjob"
	tools_x_amz_target_sagemaker_listalgorithms "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listalgorithms"
	tools_x_amz_target_sagemaker_updateappimageconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateappimageconfig"
	tools_x_amz_target_sagemaker_describemodelpackage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describemodelpackage"
	tools_x_amz_target_sagemaker_createcontext "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createcontext"
	tools_x_amz_target_sagemaker_liststagedevices "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_liststagedevices"
	tools_x_amz_target_sagemaker_listmodelmetadata "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelmetadata"
	tools_x_amz_target_sagemaker_deletemodelcard "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelcard"
	tools_x_amz_target_sagemaker_deregisterdevices "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deregisterdevices"
	tools_x_amz_target_sagemaker_createcompilationjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createcompilationjob"
	tools_x_amz_target_sagemaker_listimages "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listimages"
	tools_x_amz_target_sagemaker_updateuserprofile "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateuserprofile"
	tools_x_amz_target_sagemaker_createdataqualityjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createdataqualityjobdefinition"
	tools_x_amz_target_sagemaker_deletehumantaskui "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletehumantaskui"
	tools_x_amz_target_sagemaker_disassociatetrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_disassociatetrialcomponent"
	tools_x_amz_target_sagemaker_createstudiolifecycleconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createstudiolifecycleconfig"
	tools_x_amz_target_sagemaker_deleteappimageconfig "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteappimageconfig"
	tools_x_amz_target_sagemaker_createtrainingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createtrainingjob"
	tools_x_amz_target_sagemaker_createmodelbiasjobdefinition "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelbiasjobdefinition"
	tools_x_amz_target_sagemaker_deleteworkforce "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteworkforce"
	tools_x_amz_target_sagemaker_deleteimageversion "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteimageversion"
	tools_x_amz_target_sagemaker_listmodelpackagegroups "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmodelpackagegroups"
	tools_x_amz_target_sagemaker_deleteuserprofile "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteuserprofile"
	tools_x_amz_target_sagemaker_deleteedgedeploymentplan "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deleteedgedeploymentplan"
	tools_x_amz_target_sagemaker_deletemodelpackagegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletemodelpackagegroup"
	tools_x_amz_target_sagemaker_disablesagemakerservicecatalogportfolio "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_disablesagemakerservicecatalogportfolio"
	tools_x_amz_target_sagemaker_associatetrialcomponent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_associatetrialcomponent"
	tools_x_amz_target_sagemaker_listprojects "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listprojects"
	tools_x_amz_target_sagemaker_listmonitoringalerts "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listmonitoringalerts"
	tools_x_amz_target_sagemaker_listhyperparametertuningjobs "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listhyperparametertuningjobs"
	tools_x_amz_target_sagemaker_createprocessingjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createprocessingjob"
	tools_x_amz_target_sagemaker_listcandidatesforautomljob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listcandidatesforautomljob"
	tools_x_amz_target_sagemaker_createfeaturegroup "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createfeaturegroup"
	tools_x_amz_target_sagemaker_describehubcontent "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describehubcontent"
	tools_x_amz_target_sagemaker_createmodelpackage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createmodelpackage"
	tools_x_amz_target_sagemaker_deletecoderepository "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletecoderepository"
	tools_x_amz_target_sagemaker_createautomljobv2 "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createautomljobv2"
	tools_x_amz_target_sagemaker_deletespace "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_deletespace"
	tools_x_amz_target_sagemaker_enablesagemakerservicecatalogportfolio "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_enablesagemakerservicecatalogportfolio"
	tools_x_amz_target_sagemaker_listpipelineexecutions "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_listpipelineexecutions"
	tools_x_amz_target_sagemaker_updateworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_updateworkteam"
	tools_x_amz_target_sagemaker_describepipeline "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describepipeline"
	tools_x_amz_target_sagemaker_describecontext "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_describecontext"
	tools_x_amz_target_sagemaker_createedgedeploymentstage "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createedgedeploymentstage"
	tools_x_amz_target_sagemaker_stoppipelineexecution "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_stoppipelineexecution"
	tools_x_amz_target_sagemaker_createinferencerecommendationsjob "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createinferencerecommendationsjob"
	tools_x_amz_target_sagemaker_createworkteam "github.com/amazon-sagemaker-service/mcp-server/tools/x_amz_target_sagemaker_createworkteam"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_sagemaker_describemodelbiasjobdefinition.CreateDescribemodelbiasjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_describeworkforce.CreateDescribeworkforceTool(cfg),
		tools_x_amz_target_sagemaker_describetrial.CreateDescribetrialTool(cfg),
		tools_x_amz_target_sagemaker_describealgorithm.CreateDescribealgorithmTool(cfg),
		tools_x_amz_target_sagemaker_listworkforces.CreateListworkforcesTool(cfg),
		tools_x_amz_target_sagemaker_deletestudiolifecycleconfig.CreateDeletestudiolifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_describelabelingjob.CreateDescribelabelingjobTool(cfg),
		tools_x_amz_target_sagemaker_deletenotebookinstancelifecycleconfig.CreateDeletenotebookinstancelifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_listhubcontents.CreateListhubcontentsTool(cfg),
		tools_x_amz_target_sagemaker_listtransformjobs.CreateListtransformjobsTool(cfg),
		tools_x_amz_target_sagemaker_describeimage.CreateDescribeimageTool(cfg),
		tools_x_amz_target_sagemaker_listexperiments.CreateListexperimentsTool(cfg),
		tools_x_amz_target_sagemaker_createproject.CreateCreateprojectTool(cfg),
		tools_x_amz_target_sagemaker_listcompilationjobs.CreateListcompilationjobsTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelexplainabilityjobdefinition.CreateDeletemodelexplainabilityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_describeimageversion.CreateDescribeimageversionTool(cfg),
		tools_x_amz_target_sagemaker_listlabelingjobs.CreateListlabelingjobsTool(cfg),
		tools_x_amz_target_sagemaker_createendpoint.CreateCreateendpointTool(cfg),
		tools_x_amz_target_sagemaker_listspaces.CreateListspacesTool(cfg),
		tools_x_amz_target_sagemaker_updatetrainingjob.CreateUpdatetrainingjobTool(cfg),
		tools_x_amz_target_sagemaker_listmodelcardexportjobs.CreateListmodelcardexportjobsTool(cfg),
		tools_x_amz_target_sagemaker_describeedgepackagingjob.CreateDescribeedgepackagingjobTool(cfg),
		tools_x_amz_target_sagemaker_updatemonitoringschedule.CreateUpdatemonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_listsubscribedworkteams.CreateListsubscribedworkteamsTool(cfg),
		tools_x_amz_target_sagemaker_updateendpointweightsandcapacities.CreateUpdateendpointweightsandcapacitiesTool(cfg),
		tools_x_amz_target_sagemaker_listmonitoringexecutions.CreateListmonitoringexecutionsTool(cfg),
		tools_x_amz_target_sagemaker_createaction.CreateCreateactionTool(cfg),
		tools_x_amz_target_sagemaker_registerdevices.CreateRegisterdevicesTool(cfg),
		tools_x_amz_target_sagemaker_createexperiment.CreateCreateexperimentTool(cfg),
		tools_x_amz_target_sagemaker_describeappimageconfig.CreateDescribeappimageconfigTool(cfg),
		tools_x_amz_target_sagemaker_describefeaturegroup.CreateDescribefeaturegroupTool(cfg),
		tools_x_amz_target_sagemaker_deleteartifact.CreateDeleteartifactTool(cfg),
		tools_x_amz_target_sagemaker_listlabelingjobsforworkteam.CreateListlabelingjobsforworkteamTool(cfg),
		tools_x_amz_target_sagemaker_createdomain.CreateCreatedomainTool(cfg),
		tools_x_amz_target_sagemaker_createtrialcomponent.CreateCreatetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_listimageversions.CreateListimageversionsTool(cfg),
		tools_x_amz_target_sagemaker_describeedgedeploymentplan.CreateDescribeedgedeploymentplanTool(cfg),
		tools_x_amz_target_sagemaker_updateaction.CreateUpdateactionTool(cfg),
		tools_x_amz_target_sagemaker_deletetags.CreateDeletetagsTool(cfg),
		tools_x_amz_target_sagemaker_deletemodel.CreateDeletemodelTool(cfg),
		tools_x_amz_target_sagemaker_describeendpoint.CreateDescribeendpointTool(cfg),
		tools_x_amz_target_sagemaker_describeapp.CreateDescribeappTool(cfg),
		tools_x_amz_target_sagemaker_createimageversion.CreateCreateimageversionTool(cfg),
		tools_x_amz_target_sagemaker_listmonitoringschedules.CreateListmonitoringschedulesTool(cfg),
		tools_x_amz_target_sagemaker_updatepipeline.CreateUpdatepipelineTool(cfg),
		tools_x_amz_target_sagemaker_updateendpoint.CreateUpdateendpointTool(cfg),
		tools_x_amz_target_sagemaker_createedgepackagingjob.CreateCreateedgepackagingjobTool(cfg),
		tools_x_amz_target_sagemaker_describeproject.CreateDescribeprojectTool(cfg),
		tools_x_amz_target_sagemaker_describemonitoringschedule.CreateDescribemonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_deleteendpoint.CreateDeleteendpointTool(cfg),
		tools_x_amz_target_sagemaker_updatetrialcomponent.CreateUpdatetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_listhubcontentversions.CreateListhubcontentversionsTool(cfg),
		tools_x_amz_target_sagemaker_stopnotebookinstance.CreateStopnotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_listdataqualityjobdefinitions.CreateListdataqualityjobdefinitionsTool(cfg),
		tools_x_amz_target_sagemaker_listartifacts.CreateListartifactsTool(cfg),
		tools_x_amz_target_sagemaker_updatecontext.CreateUpdatecontextTool(cfg),
		tools_x_amz_target_sagemaker_deleteproject.CreateDeleteprojectTool(cfg),
		tools_x_amz_target_sagemaker_describeexperiment.CreateDescribeexperimentTool(cfg),
		tools_x_amz_target_sagemaker_describetrainingjob.CreateDescribetrainingjobTool(cfg),
		tools_x_amz_target_sagemaker_listaliases.CreateListaliasesTool(cfg),
		tools_x_amz_target_sagemaker_deletefeaturegroup.CreateDeletefeaturegroupTool(cfg),
		tools_x_amz_target_sagemaker_listtrainingjobs.CreateListtrainingjobsTool(cfg),
		tools_x_amz_target_sagemaker_describemodelcard.CreateDescribemodelcardTool(cfg),
		tools_x_amz_target_sagemaker_updatetrial.CreateUpdatetrialTool(cfg),
		tools_x_amz_target_sagemaker_listresourcecatalogs.CreateListresourcecatalogsTool(cfg),
		tools_x_amz_target_sagemaker_updateartifact.CreateUpdateartifactTool(cfg),
		tools_x_amz_target_sagemaker_listactions.CreateListactionsTool(cfg),
		tools_x_amz_target_sagemaker_createnotebookinstancelifecycleconfig.CreateCreatenotebookinstancelifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_listuserprofiles.CreateListuserprofilesTool(cfg),
		tools_x_amz_target_sagemaker_listhubs.CreateListhubsTool(cfg),
		tools_x_amz_target_sagemaker_deleteworkteam.CreateDeleteworkteamTool(cfg),
		tools_x_amz_target_sagemaker_createalgorithm.CreateCreatealgorithmTool(cfg),
		tools_x_amz_target_sagemaker_startinferenceexperiment.CreateStartinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_startpipelineexecution.CreateStartpipelineexecutionTool(cfg),
		tools_x_amz_target_sagemaker_updatespace.CreateUpdatespaceTool(cfg),
		tools_x_amz_target_sagemaker_deleteedgedeploymentstage.CreateDeleteedgedeploymentstageTool(cfg),
		tools_x_amz_target_sagemaker_updateinferenceexperiment.CreateUpdateinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_updatecoderepository.CreateUpdatecoderepositoryTool(cfg),
		tools_x_amz_target_sagemaker_listappimageconfigs.CreateListappimageconfigsTool(cfg),
		tools_x_amz_target_sagemaker_updateworkforce.CreateUpdateworkforceTool(cfg),
		tools_x_amz_target_sagemaker_updatepipelineexecution.CreateUpdatepipelineexecutionTool(cfg),
		tools_x_amz_target_sagemaker_listdevices.CreateListdevicesTool(cfg),
		tools_x_amz_target_sagemaker_stopcompilationjob.CreateStopcompilationjobTool(cfg),
		tools_x_amz_target_sagemaker_createmodelexplainabilityjobdefinition.CreateCreatemodelexplainabilityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_describemodelcardexportjob.CreateDescribemodelcardexportjobTool(cfg),
		tools_x_amz_target_sagemaker_updatehub.CreateUpdatehubTool(cfg),
		tools_x_amz_target_sagemaker_updatedomain.CreateUpdatedomainTool(cfg),
		tools_x_amz_target_sagemaker_updateproject.CreateUpdateprojectTool(cfg),
		tools_x_amz_target_sagemaker_stopinferenceexperiment.CreateStopinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_createappimageconfig.CreateCreateappimageconfigTool(cfg),
		tools_x_amz_target_sagemaker_describeprocessingjob.CreateDescribeprocessingjobTool(cfg),
		tools_x_amz_target_sagemaker_listtrainingjobsforhyperparametertuningjob.CreateListtrainingjobsforhyperparametertuningjobTool(cfg),
		tools_x_amz_target_sagemaker_deletedomain.CreateDeletedomainTool(cfg),
		tools_x_amz_target_sagemaker_listflowdefinitions.CreateListflowdefinitionsTool(cfg),
		tools_x_amz_target_sagemaker_createpresignednotebookinstanceurl.CreateCreatepresignednotebookinstanceurlTool(cfg),
		tools_x_amz_target_sagemaker_describeartifact.CreateDescribeartifactTool(cfg),
		tools_x_amz_target_sagemaker_createdevicefleet.CreateCreatedevicefleetTool(cfg),
		tools_x_amz_target_sagemaker_stopautomljob.CreateStopautomljobTool(cfg),
		tools_x_amz_target_sagemaker_updatedevices.CreateUpdatedevicesTool(cfg),
		tools_x_amz_target_sagemaker_updatemodelcard.CreateUpdatemodelcardTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelpackagegrouppolicy.CreateDeletemodelpackagegrouppolicyTool(cfg),
		tools_x_amz_target_sagemaker_deleteinferenceexperiment.CreateDeleteinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_getsagemakerservicecatalogportfoliostatus.CreateGetsagemakerservicecatalogportfoliostatusTool(cfg),
		tools_x_amz_target_sagemaker_getsearchsuggestions.CreateGetsearchsuggestionsTool(cfg),
		tools_x_amz_target_sagemaker_addassociation.CreateAddassociationTool(cfg),
		tools_x_amz_target_sagemaker_describemodelexplainabilityjobdefinition.CreateDescribemodelexplainabilityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_describeworkteam.CreateDescribeworkteamTool(cfg),
		tools_x_amz_target_sagemaker_describeautomljobv2.CreateDescribeautomljobv2Tool(cfg),
		tools_x_amz_target_sagemaker_createinferenceexperiment.CreateCreateinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_createuserprofile.CreateCreateuserprofileTool(cfg),
		tools_x_amz_target_sagemaker_listinferenceexperiments.CreateListinferenceexperimentsTool(cfg),
		tools_x_amz_target_sagemaker_describeautomljob.CreateDescribeautomljobTool(cfg),
		tools_x_amz_target_sagemaker_stoplabelingjob.CreateStoplabelingjobTool(cfg),
		tools_x_amz_target_sagemaker_describeinferencerecommendationsjob.CreateDescribeinferencerecommendationsjobTool(cfg),
		tools_x_amz_target_sagemaker_describemodel.CreateDescribemodelTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelpackage.CreateDeletemodelpackageTool(cfg),
		tools_x_amz_target_sagemaker_createpresigneddomainurl.CreateCreatepresigneddomainurlTool(cfg),
		tools_x_amz_target_sagemaker_updateexperiment.CreateUpdateexperimentTool(cfg),
		tools_x_amz_target_sagemaker_stopmonitoringschedule.CreateStopmonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_describespace.CreateDescribespaceTool(cfg),
		tools_x_amz_target_sagemaker_listapps.CreateListappsTool(cfg),
		tools_x_amz_target_sagemaker_updatemodelpackage.CreateUpdatemodelpackageTool(cfg),
		tools_x_amz_target_sagemaker_describeflowdefinition.CreateDescribeflowdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_listedgedeploymentplans.CreateListedgedeploymentplansTool(cfg),
		tools_x_amz_target_sagemaker_createhub.CreateCreatehubTool(cfg),
		tools_x_amz_target_sagemaker_listworkteams.CreateListworkteamsTool(cfg),
		tools_x_amz_target_sagemaker_listfeaturegroups.CreateListfeaturegroupsTool(cfg),
		tools_x_amz_target_sagemaker_stopprocessingjob.CreateStopprocessingjobTool(cfg),
		tools_x_amz_target_sagemaker_describepipelinedefinitionforexecution.CreateDescribepipelinedefinitionforexecutionTool(cfg),
		tools_x_amz_target_sagemaker_listhumantaskuis.CreateListhumantaskuisTool(cfg),
		tools_x_amz_target_sagemaker_listmodelcards.CreateListmodelcardsTool(cfg),
		tools_x_amz_target_sagemaker_describeuserprofile.CreateDescribeuserprofileTool(cfg),
		tools_x_amz_target_sagemaker_createcoderepository.CreateCreatecoderepositoryTool(cfg),
		tools_x_amz_target_sagemaker_listnotebookinstances.CreateListnotebookinstancesTool(cfg),
		tools_x_amz_target_sagemaker_deletetrialcomponent.CreateDeletetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_listassociations.CreateListassociationsTool(cfg),
		tools_x_amz_target_sagemaker_listedgepackagingjobs.CreateListedgepackagingjobsTool(cfg),
		tools_x_amz_target_sagemaker_stoptransformjob.CreateStoptransformjobTool(cfg),
		tools_x_amz_target_sagemaker_deletenotebookinstance.CreateDeletenotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_sendpipelineexecutionstepfailure.CreateSendpipelineexecutionstepfailureTool(cfg),
		tools_x_amz_target_sagemaker_listtrialcomponents.CreateListtrialcomponentsTool(cfg),
		tools_x_amz_target_sagemaker_describedataqualityjobdefinition.CreateDescribedataqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_describenotebookinstance.CreateDescribenotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_deleteimage.CreateDeleteimageTool(cfg),
		tools_x_amz_target_sagemaker_createworkforce.CreateCreateworkforceTool(cfg),
		tools_x_amz_target_sagemaker_createimage.CreateCreateimageTool(cfg),
		tools_x_amz_target_sagemaker_createartifact.CreateCreateartifactTool(cfg),
		tools_x_amz_target_sagemaker_createapp.CreateCreateappTool(cfg),
		tools_x_amz_target_sagemaker_listmodelexplainabilityjobdefinitions.CreateListmodelexplainabilityjobdefinitionsTool(cfg),
		tools_x_amz_target_sagemaker_deletetrial.CreateDeletetrialTool(cfg),
		tools_x_amz_target_sagemaker_createedgedeploymentplan.CreateCreateedgedeploymentplanTool(cfg),
		tools_x_amz_target_sagemaker_deleteflowdefinition.CreateDeleteflowdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_deletealgorithm.CreateDeletealgorithmTool(cfg),
		tools_x_amz_target_sagemaker_listmodelcardversions.CreateListmodelcardversionsTool(cfg),
		tools_x_amz_target_sagemaker_listprocessingjobs.CreateListprocessingjobsTool(cfg),
		tools_x_amz_target_sagemaker_createmodelqualityjobdefinition.CreateCreatemodelqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_deletemonitoringschedule.CreateDeletemonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_describenotebookinstancelifecycleconfig.CreateDescribenotebookinstancelifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_putmodelpackagegrouppolicy.CreatePutmodelpackagegrouppolicyTool(cfg),
		tools_x_amz_target_sagemaker_deleteendpointconfig.CreateDeleteendpointconfigTool(cfg),
		tools_x_amz_target_sagemaker_deletepipeline.CreateDeletepipelineTool(cfg),
		tools_x_amz_target_sagemaker_createspace.CreateCreatespaceTool(cfg),
		tools_x_amz_target_sagemaker_createmodel.CreateCreatemodelTool(cfg),
		tools_x_amz_target_sagemaker_stopedgepackagingjob.CreateStopedgepackagingjobTool(cfg),
		tools_x_amz_target_sagemaker_deleteapp.CreateDeleteappTool(cfg),
		tools_x_amz_target_sagemaker_startedgedeploymentstage.CreateStartedgedeploymentstageTool(cfg),
		tools_x_amz_target_sagemaker_liststudiolifecycleconfigs.CreateListstudiolifecycleconfigsTool(cfg),
		tools_x_amz_target_sagemaker_createhyperparametertuningjob.CreateCreatehyperparametertuningjobTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelqualityjobdefinition.CreateDeletemodelqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_listpipelineparametersforexecution.CreateListpipelineparametersforexecutionTool(cfg),
		tools_x_amz_target_sagemaker_describeendpointconfig.CreateDescribeendpointconfigTool(cfg),
		tools_x_amz_target_sagemaker_updateimageversion.CreateUpdateimageversionTool(cfg),
		tools_x_amz_target_sagemaker_updatenotebookinstance.CreateUpdatenotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_search.CreateSearchTool(cfg),
		tools_x_amz_target_sagemaker_createmodelpackagegroup.CreateCreatemodelpackagegroupTool(cfg),
		tools_x_amz_target_sagemaker_createpipeline.CreateCreatepipelineTool(cfg),
		tools_x_amz_target_sagemaker_stophyperparametertuningjob.CreateStophyperparametertuningjobTool(cfg),
		tools_x_amz_target_sagemaker_retrypipelineexecution.CreateRetrypipelineexecutionTool(cfg),
		tools_x_amz_target_sagemaker_getlineagegrouppolicy.CreateGetlineagegrouppolicyTool(cfg),
		tools_x_amz_target_sagemaker_listdevicefleets.CreateListdevicefleetsTool(cfg),
		tools_x_amz_target_sagemaker_updatedevicefleet.CreateUpdatedevicefleetTool(cfg),
		tools_x_amz_target_sagemaker_describetrialcomponent.CreateDescribetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_deletehub.CreateDeletehubTool(cfg),
		tools_x_amz_target_sagemaker_listcontexts.CreateListcontextsTool(cfg),
		tools_x_amz_target_sagemaker_stopedgedeploymentstage.CreateStopedgedeploymentstageTool(cfg),
		tools_x_amz_target_sagemaker_listcoderepositories.CreateListcoderepositoriesTool(cfg),
		tools_x_amz_target_sagemaker_createtransformjob.CreateCreatetransformjobTool(cfg),
		tools_x_amz_target_sagemaker_describemodelpackagegroup.CreateDescribemodelpackagegroupTool(cfg),
		tools_x_amz_target_sagemaker_listmodels.CreateListmodelsTool(cfg),
		tools_x_amz_target_sagemaker_describeaction.CreateDescribeactionTool(cfg),
		tools_x_amz_target_sagemaker_updateimage.CreateUpdateimageTool(cfg),
		tools_x_amz_target_sagemaker_describelineagegroup.CreateDescribelineagegroupTool(cfg),
		tools_x_amz_target_sagemaker_startnotebookinstance.CreateStartnotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_listlineagegroups.CreateListlineagegroupsTool(cfg),
		tools_x_amz_target_sagemaker_createtrial.CreateCreatetrialTool(cfg),
		tools_x_amz_target_sagemaker_describecoderepository.CreateDescribecoderepositoryTool(cfg),
		tools_x_amz_target_sagemaker_listnotebookinstancelifecycleconfigs.CreateListnotebookinstancelifecycleconfigsTool(cfg),
		tools_x_amz_target_sagemaker_createmonitoringschedule.CreateCreatemonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_listendpointconfigs.CreateListendpointconfigsTool(cfg),
		tools_x_amz_target_sagemaker_deletecontext.CreateDeletecontextTool(cfg),
		tools_x_amz_target_sagemaker_listautomljobs.CreateListautomljobsTool(cfg),
		tools_x_amz_target_sagemaker_listtrials.CreateListtrialsTool(cfg),
		tools_x_amz_target_sagemaker_createnotebookinstance.CreateCreatenotebookinstanceTool(cfg),
		tools_x_amz_target_sagemaker_describehub.CreateDescribehubTool(cfg),
		tools_x_amz_target_sagemaker_listtags.CreateListtagsTool(cfg),
		tools_x_amz_target_sagemaker_deletedataqualityjobdefinition.CreateDeletedataqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_createautomljob.CreateCreateautomljobTool(cfg),
		tools_x_amz_target_sagemaker_describestudiolifecycleconfig.CreateDescribestudiolifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_describehyperparametertuningjob.CreateDescribehyperparametertuningjobTool(cfg),
		tools_x_amz_target_sagemaker_startmonitoringschedule.CreateStartmonitoringscheduleTool(cfg),
		tools_x_amz_target_sagemaker_deleteassociation.CreateDeleteassociationTool(cfg),
		tools_x_amz_target_sagemaker_querylineage.CreateQuerylineageTool(cfg),
		tools_x_amz_target_sagemaker_listpipelines.CreateListpipelinesTool(cfg),
		tools_x_amz_target_sagemaker_describedomain.CreateDescribedomainTool(cfg),
		tools_x_amz_target_sagemaker_updatemonitoringalert.CreateUpdatemonitoringalertTool(cfg),
		tools_x_amz_target_sagemaker_deletedevicefleet.CreateDeletedevicefleetTool(cfg),
		tools_x_amz_target_sagemaker_updatefeaturemetadata.CreateUpdatefeaturemetadataTool(cfg),
		tools_x_amz_target_sagemaker_listdomains.CreateListdomainsTool(cfg),
		tools_x_amz_target_sagemaker_sendpipelineexecutionstepsuccess.CreateSendpipelineexecutionstepsuccessTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelbiasjobdefinition.CreateDeletemodelbiasjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_addtags.CreateAddtagsTool(cfg),
		tools_x_amz_target_sagemaker_listinferencerecommendationsjobsteps.CreateListinferencerecommendationsjobstepsTool(cfg),
		tools_x_amz_target_sagemaker_getdevicefleetreport.CreateGetdevicefleetreportTool(cfg),
		tools_x_amz_target_sagemaker_listmodelqualityjobdefinitions.CreateListmodelqualityjobdefinitionsTool(cfg),
		tools_x_amz_target_sagemaker_getscalingconfigurationrecommendation.CreateGetscalingconfigurationrecommendationTool(cfg),
		tools_x_amz_target_sagemaker_createlabelingjob.CreateCreatelabelingjobTool(cfg),
		tools_x_amz_target_sagemaker_describehumantaskui.CreateDescribehumantaskuiTool(cfg),
		tools_x_amz_target_sagemaker_createflowdefinition.CreateCreateflowdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_deleteexperiment.CreateDeleteexperimentTool(cfg),
		tools_x_amz_target_sagemaker_stopinferencerecommendationsjob.CreateStopinferencerecommendationsjobTool(cfg),
		tools_x_amz_target_sagemaker_createmodelcardexportjob.CreateCreatemodelcardexportjobTool(cfg),
		tools_x_amz_target_sagemaker_getmodelpackagegrouppolicy.CreateGetmodelpackagegrouppolicyTool(cfg),
		tools_x_amz_target_sagemaker_describepipelineexecution.CreateDescribepipelineexecutionTool(cfg),
		tools_x_amz_target_sagemaker_listinferencerecommendationsjobs.CreateListinferencerecommendationsjobsTool(cfg),
		tools_x_amz_target_sagemaker_describeinferenceexperiment.CreateDescribeinferenceexperimentTool(cfg),
		tools_x_amz_target_sagemaker_listendpoints.CreateListendpointsTool(cfg),
		tools_x_amz_target_sagemaker_listmodelpackages.CreateListmodelpackagesTool(cfg),
		tools_x_amz_target_sagemaker_batchdescribemodelpackage.CreateBatchdescribemodelpackageTool(cfg),
		tools_x_amz_target_sagemaker_createhumantaskui.CreateCreatehumantaskuiTool(cfg),
		tools_x_amz_target_sagemaker_stoptrainingjob.CreateStoptrainingjobTool(cfg),
		tools_x_amz_target_sagemaker_describesubscribedworkteam.CreateDescribesubscribedworkteamTool(cfg),
		tools_x_amz_target_sagemaker_renderuitemplate.CreateRenderuitemplateTool(cfg),
		tools_x_amz_target_sagemaker_updatenotebookinstancelifecycleconfig.CreateUpdatenotebookinstancelifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_createmodelcard.CreateCreatemodelcardTool(cfg),
		tools_x_amz_target_sagemaker_describemodelqualityjobdefinition.CreateDescribemodelqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_updatefeaturegroup.CreateUpdatefeaturegroupTool(cfg),
		tools_x_amz_target_sagemaker_describefeaturemetadata.CreateDescribefeaturemetadataTool(cfg),
		tools_x_amz_target_sagemaker_createendpointconfig.CreateCreateendpointconfigTool(cfg),
		tools_x_amz_target_sagemaker_listmodelbiasjobdefinitions.CreateListmodelbiasjobdefinitionsTool(cfg),
		tools_x_amz_target_sagemaker_importhubcontent.CreateImporthubcontentTool(cfg),
		tools_x_amz_target_sagemaker_listpipelineexecutionsteps.CreateListpipelineexecutionstepsTool(cfg),
		tools_x_amz_target_sagemaker_describecompilationjob.CreateDescribecompilationjobTool(cfg),
		tools_x_amz_target_sagemaker_describedevicefleet.CreateDescribedevicefleetTool(cfg),
		tools_x_amz_target_sagemaker_describedevice.CreateDescribedeviceTool(cfg),
		tools_x_amz_target_sagemaker_listmonitoringalerthistory.CreateListmonitoringalerthistoryTool(cfg),
		tools_x_amz_target_sagemaker_deleteaction.CreateDeleteactionTool(cfg),
		tools_x_amz_target_sagemaker_deletehubcontent.CreateDeletehubcontentTool(cfg),
		tools_x_amz_target_sagemaker_describetransformjob.CreateDescribetransformjobTool(cfg),
		tools_x_amz_target_sagemaker_listalgorithms.CreateListalgorithmsTool(cfg),
		tools_x_amz_target_sagemaker_updateappimageconfig.CreateUpdateappimageconfigTool(cfg),
		tools_x_amz_target_sagemaker_describemodelpackage.CreateDescribemodelpackageTool(cfg),
		tools_x_amz_target_sagemaker_createcontext.CreateCreatecontextTool(cfg),
		tools_x_amz_target_sagemaker_liststagedevices.CreateListstagedevicesTool(cfg),
		tools_x_amz_target_sagemaker_listmodelmetadata.CreateListmodelmetadataTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelcard.CreateDeletemodelcardTool(cfg),
		tools_x_amz_target_sagemaker_deregisterdevices.CreateDeregisterdevicesTool(cfg),
		tools_x_amz_target_sagemaker_createcompilationjob.CreateCreatecompilationjobTool(cfg),
		tools_x_amz_target_sagemaker_listimages.CreateListimagesTool(cfg),
		tools_x_amz_target_sagemaker_updateuserprofile.CreateUpdateuserprofileTool(cfg),
		tools_x_amz_target_sagemaker_createdataqualityjobdefinition.CreateCreatedataqualityjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_deletehumantaskui.CreateDeletehumantaskuiTool(cfg),
		tools_x_amz_target_sagemaker_disassociatetrialcomponent.CreateDisassociatetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_createstudiolifecycleconfig.CreateCreatestudiolifecycleconfigTool(cfg),
		tools_x_amz_target_sagemaker_deleteappimageconfig.CreateDeleteappimageconfigTool(cfg),
		tools_x_amz_target_sagemaker_createtrainingjob.CreateCreatetrainingjobTool(cfg),
		tools_x_amz_target_sagemaker_createmodelbiasjobdefinition.CreateCreatemodelbiasjobdefinitionTool(cfg),
		tools_x_amz_target_sagemaker_deleteworkforce.CreateDeleteworkforceTool(cfg),
		tools_x_amz_target_sagemaker_deleteimageversion.CreateDeleteimageversionTool(cfg),
		tools_x_amz_target_sagemaker_listmodelpackagegroups.CreateListmodelpackagegroupsTool(cfg),
		tools_x_amz_target_sagemaker_deleteuserprofile.CreateDeleteuserprofileTool(cfg),
		tools_x_amz_target_sagemaker_deleteedgedeploymentplan.CreateDeleteedgedeploymentplanTool(cfg),
		tools_x_amz_target_sagemaker_deletemodelpackagegroup.CreateDeletemodelpackagegroupTool(cfg),
		tools_x_amz_target_sagemaker_disablesagemakerservicecatalogportfolio.CreateDisablesagemakerservicecatalogportfolioTool(cfg),
		tools_x_amz_target_sagemaker_associatetrialcomponent.CreateAssociatetrialcomponentTool(cfg),
		tools_x_amz_target_sagemaker_listprojects.CreateListprojectsTool(cfg),
		tools_x_amz_target_sagemaker_listmonitoringalerts.CreateListmonitoringalertsTool(cfg),
		tools_x_amz_target_sagemaker_listhyperparametertuningjobs.CreateListhyperparametertuningjobsTool(cfg),
		tools_x_amz_target_sagemaker_createprocessingjob.CreateCreateprocessingjobTool(cfg),
		tools_x_amz_target_sagemaker_listcandidatesforautomljob.CreateListcandidatesforautomljobTool(cfg),
		tools_x_amz_target_sagemaker_createfeaturegroup.CreateCreatefeaturegroupTool(cfg),
		tools_x_amz_target_sagemaker_describehubcontent.CreateDescribehubcontentTool(cfg),
		tools_x_amz_target_sagemaker_createmodelpackage.CreateCreatemodelpackageTool(cfg),
		tools_x_amz_target_sagemaker_deletecoderepository.CreateDeletecoderepositoryTool(cfg),
		tools_x_amz_target_sagemaker_createautomljobv2.CreateCreateautomljobv2Tool(cfg),
		tools_x_amz_target_sagemaker_deletespace.CreateDeletespaceTool(cfg),
		tools_x_amz_target_sagemaker_enablesagemakerservicecatalogportfolio.CreateEnablesagemakerservicecatalogportfolioTool(cfg),
		tools_x_amz_target_sagemaker_listpipelineexecutions.CreateListpipelineexecutionsTool(cfg),
		tools_x_amz_target_sagemaker_updateworkteam.CreateUpdateworkteamTool(cfg),
		tools_x_amz_target_sagemaker_describepipeline.CreateDescribepipelineTool(cfg),
		tools_x_amz_target_sagemaker_describecontext.CreateDescribecontextTool(cfg),
		tools_x_amz_target_sagemaker_createedgedeploymentstage.CreateCreateedgedeploymentstageTool(cfg),
		tools_x_amz_target_sagemaker_stoppipelineexecution.CreateStoppipelineexecutionTool(cfg),
		tools_x_amz_target_sagemaker_createinferencerecommendationsjob.CreateCreateinferencerecommendationsjobTool(cfg),
		tools_x_amz_target_sagemaker_createworkteam.CreateCreateworkteamTool(cfg),
	}
}
